version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: true
permissions: 
  - object: /home/ubuntu/app
    pattern: "*.sh"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
     - file
hooks:
  ApplicationStart:
    - location: /home/ubuntu/app/deploy.sh
      timeout: 300
      runas: ubuntu