version: 0.0
os: linux
files:
  - source: deploy.sh
    destination: /var/www/
    overwrite: true
permissions: 
  - object: /var/www/
    pattern: "*.sh"
    owner: root
    group: root
    mode: 755
    type:
     - file
hooks:
  ApplicationStart:
    -location: /var/www/deploy.sh
    timeout: 120


