version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/
    overwrite: true
permissions:
  - object: /var/www/
    pattern: "*.sh"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
     - file
hooks:
  ApplicationStart:
    - location: /deploy.sh
      timeout: 300
      runas: ubuntu