version: 0.0
os: linux
files:
  - source: /
    destination: /app
    overwrite: true
permissions: 
  - object: /app
    pattern: "*.sh"
    owner: root
    group: root
    mode: 755
    type:
     - file
hooks:
  ApplicationStart:
    -location: /app/deploy.sh
    timeout: 300


