version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - apt-get update -y
      - apt-get install build-essential
      - apt install -y nodejs node-gyp libssl1.0-dev
      - apt install -y sqlite3
      - apt install -y npm
      - apt install -y python3.7
      - node --version
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
      - echo "Building App"
      - npm install -g npm@latest
      - echo "Building Docker Image"
      - docker build --rm -t timeoff:latest --no-cache .
  post_build:
    commands:
      - echo "Entered the post-build phase"
      - echo "Running Docker Image"
      #- docker run -t -i -d -p 3000:3000 --name alpine_timeoff timeoff
      - chmod +x deploy.sh
artifacts:
  files:
    #- docker
    - '**/*'
    #- package.json
    #- appspec.yml
    #- deploy.sh
    #- Dockerfile
    #- Dockerrun.aws.json
